In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv("FIFA.csv")

In [5]:
fifa = data.copy()

In [34]:
fifa.head()

,Unnamed: 0,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,0,Cristiano Ronaldo,32,https://cdn.sofifa.org/48/18/players/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,1,L. Messi,30,https://cdn.sofifa.org/48/18/players/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,93,93,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,...,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,2,Neymar,25,https://cdn.sofifa.org/48/18/players/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,94,Paris Saint-Germain,https://cdn.sofifa.org/24/18/teams/73.png,...,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,3,L. SuÃ¡rez,30,https://cdn.sofifa.org/48/18/players/176580.png,Uruguay,https://cdn.sofifa.org/flags/60.png,92,92,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,4,M. Neuer,31,https://cdn.sofifa.org/48/18/players/167495.png,Germany,https://cdn.sofifa.org/flags/21.png,92,92,FC Bayern Munich,https://cdn.sofifa.org/24/18/teams/21.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
fifa.tail()

,Unnamed: 0,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
17976,17976,A. Kelsey,17,https://cdn.sofifa.org/48/18/players/237463.png,England,https://cdn.sofifa.org/flags/14.png,46,63,Scunthorpe United,https://cdn.sofifa.org/24/18/teams/1949.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17977,17977,B. Richardson,47,https://cdn.sofifa.org/48/18/players/11728.png,England,https://cdn.sofifa.org/flags/14.png,46,46,Wycombe Wanderers,https://cdn.sofifa.org/24/18/teams/1933.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17978,17978,J. Young,17,https://cdn.sofifa.org/48/18/players/231381.png,Scotland,https://cdn.sofifa.org/flags/42.png,46,61,Swindon Town,https://cdn.sofifa.org/24/18/teams/1934.png,...,31.0,28.0,38.0,29.0,45.0,42.0,45.0,44.0,32.0,45.0
17979,17979,J. Lundstram,18,https://cdn.sofifa.org/48/18/players/238813.png,England,https://cdn.sofifa.org/flags/14.png,46,64,Crewe Alexandra,https://cdn.sofifa.org/24/18/teams/121.png,...,47.0,46.0,45.0,47.0,43.0,45.0,41.0,44.0,46.0,41.0
17980,17980,L. Sackey,18,https://cdn.sofifa.org/48/18/players/238308.png,Ghana,https://cdn.sofifa.org/flags/117.png,46,64,Scunthorpe United,https://cdn.sofifa.org/24/18/teams/1949.png,...,40.0,45.0,30.0,38.0,29.0,30.0,31.0,29.0,38.0,31.0

In [12]:
fifa.shape
# 17981 Rows and 74 Columns

(17981, 74)

In [16]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 74 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17981 non-null  int64
 1   Name                 17981 non-null  category
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  category
 4   Nationality          17981 non-null  category
 5   Flag                 17981 non-null  category
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  category
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  object
 11  Wage                 17981 non-null  object
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  object
 14  Aggression           17981 non-null  object
 15  Agility              17981 non-null  object
 16  Balance              17981 non-null  object
 17  Ball control         17981 non-null  object
 18  Composure            17981 non-null  object
 19  Crossing             17981 non-null  object
 20  Curve                17981 non-null  object
 21  Dribbling            17981 non-null  object
 22  Finishing            17981 non-null  object
 23  Free kick accuracy   17981 non-null  object
 24  GK diving            17981 non-null  object
 25  GK handling          17981 non-null  object
 26  GK kicking           17981 non-null  object
 27  GK positioning       17981 non-null  object
 28  GK reflexes          17981 non-null  object
 29  Heading accuracy     17981 non-null  object
 30  Interceptions        17981 non-null  object
 31  Jumping              17981 non-null  object
 32  Long passing         17981 non-null  object
 33  Long shots           17981 non-null  object
 34  Marking              17981 non-null  object
 35  Penalties            17981 non-null  object
 36  Positioning          17981 non-null  object
 37  Reactions            17981 non-null  object
 38  Short passing        17981 non-null  object
 39  Shot power           17981 non-null  object
 40  Sliding tackle       17981 non-null  object
 41  Sprint speed         17981 non-null  object
 42  Stamina              17981 non-null  object
 43  Standing tackle      17981 non-null  object
 44  Strength             17981 non-null  object
 45  Vision               17981 non-null  object
 46  Volleys              17981 non-null  object
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  LAM                  15952 non-null  float64
 53  LB                   15952 non-null  float64
 54  LCB                  15952 non-null  float64
 55  LCM                  15952 non-null  float64
 56  LDM                  15952 non-null  float64
 57  LF                   15952 non-null  float64
 58  LM                   15952 non-null  float64
 59  LS                   15952 non-null  float64
 60  LW                   15952 non-null  float64
 61  LWB                  15952 non-null  float64
 62  Preferred Positions  17981 non-null  object
 63  RAM                  15952 non-null  float64
 64  RB                   15952 non-null  float64
 65  RCB                  15952 non-null  float64
 66  RCM                  15952 non-null  float64
 67  RDM                  15952 non-null  float64
 68  RF                   15952 non-null  float64
 69  RM                   15952 non-null  float64
 70  RS                   15952 non-null  float64
 71  RW                   15952 non-null  float64
 72  RWB                  15952 non-null  float64
 73  ST                   15952 non-null  float64
dtypes: category(5), float64(26), int64(5), object(38)
memory usage: 10.9+ MB

* Change the datatype for any columns in FIFA dataset that are 'object' to 'category'

### Fix Datatype(s)

We want to change any data types that are objects to category because the data is categorical. This also helps our dataframe manager storage of data better.

In [29]:
fifa[fifa.
     select_dtypes(['object']).
     columns] = fifa.select_dtypes(['object']).apply(lambda x: x.astype('category'))

In [30]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 74 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17981 non-null  int64
 1   Name                 17981 non-null  category
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  category
 4   Nationality          17981 non-null  category
 5   Flag                 17981 non-null  category
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  category
 9   Club Logo            17981 non-null  category
 10  Value                17981 non-null  category
 11  Wage                 17981 non-null  category
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  category
 14  Aggression           17981 non-null  category
 15  Agility              17981 non-null  category
 16  Balance              17981 non-null  category
 17  Ball control         17981 non-null  category
 18  Composure            17981 non-null  category
 19  Crossing             17981 non-null  category
 20  Curve                17981 non-null  category
 21  Dribbling            17981 non-null  category
 22  Finishing            17981 non-null  category
 23  Free kick accuracy   17981 non-null  category
 24  GK diving            17981 non-null  category
 25  GK handling          17981 non-null  category
 26  GK kicking           17981 non-null  category
 27  GK positioning       17981 non-null  category
 28  GK reflexes          17981 non-null  category
 29  Heading accuracy     17981 non-null  category
 30  Interceptions        17981 non-null  category
 31  Jumping              17981 non-null  category
 32  Long passing         17981 non-null  category
 33  Long shots           17981 non-null  category
 34  Marking              17981 non-null  category
 35  Penalties            17981 non-null  category
 36  Positioning          17981 non-null  category
 37  Reactions            17981 non-null  category
 38  Short passing        17981 non-null  category
 39  Shot power           17981 non-null  category
 40  Sliding tackle       17981 non-null  category
 41  Sprint speed         17981 non-null  category
 42  Stamina              17981 non-null  category
 43  Standing tackle      17981 non-null  category
 44  Strength             17981 non-null  category
 45  Vision               17981 non-null  category
 46  Volleys              17981 non-null  category
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  LAM                  15952 non-null  float64
 53  LB                   15952 non-null  float64
 54  LCB                  15952 non-null  float64
 55  LCM                  15952 non-null  float64
 56  LDM                  15952 non-null  float64
 57  LF                   15952 non-null  float64
 58  LM                   15952 non-null  float64
 59  LS                   15952 non-null  float64
 60  LW                   15952 non-null  float64
 61  LWB                  15952 non-null  float64
 62  Preferred Positions  17981 non-null  category
 63  RAM                  15952 non-null  float64
 64  RB                   15952 non-null  float64
 65  RCB                  15952 non-null  float64
 66  RCM                  15952 non-null  float64
 67  RDM                  15952 non-null  float64
 68  RF                   15952 non-null  float64
 69  RM                   15952 non-null  float64
 70  RS                   15952 non-null  float64
 71  RW                   15952 non-null  float64
 72  RWB                  15952 non-null  float64
 73  ST                   15952 non-null  float64
dtypes: category(43), float64(26), int64(5)
memory usage: 7.2 MB

Statistical Summary

In [31]:
fifa.describe()

,Unnamed: 0,Age,Overall,Potential,Special,CAM,CB,CDM,CF,CM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
count,17981.000000,17981.000000,17981.000000,17981.000000,17981.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,...,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000
mean,8990.000000,25.144541,66.247984,71.190813,1594.095100,59.251755,55.550464,56.865283,59.030028,58.506833,...,56.979689,55.550464,58.506833,56.865283,59.030028,60.057736,58.204050,59.359265,57.698721,58.204050
std,5190.811931,4.614272,6.987965,6.102199,272.151435,9.880164,12.192579,10.310178,9.926988,8.888040,...,9.791627,12.192579,8.888040,10.310178,9.926988,9.349180,9.181392,9.978084,9.142825,9.181392
min,0.000000,16.000000,46.000000,46.000000,728.000000,27.000000,25.000000,26.000000,27.000000,30.000000,...,30.000000,25.000000,30.000000,26.000000,27.000000,28.000000,31.000000,26.000000,31.000000,31.000000
25%,4495.000000,21.000000,62.000000,67.000000,1449.000000,53.000000,45.000000,49.000000,53.000000,53.000000,...,50.000000,45.000000,53.000000,49.000000,53.000000,54.000000,52.000000,53.000000,51.000000,52.000000
50%,8990.000000,25.000000,66.000000,71.000000,1633.000000,60.000000,57.000000,58.000000,60.000000,59.000000,...,58.000000,57.000000,59.000000,58.000000,60.000000,61.000000,59.000000,60.000000,58.000000,59.000000
75%,13485.000000,28.000000,71.000000,75.000000,1786.000000,66.000000,65.000000,65.000000,66.000000,65.000000,...,64.000000,65.000000,65.000000,65.000000,66.000000,67.000000,65.000000,66.000000,64.000000,65.000000
max,17980.000000,47.000000,94.000000,94.000000,2291.000000,92.000000,87.000000,85.000000,92.000000,87.000000,...,84.000000,87.000000,87.000000,85.000000,92.000000,90.000000,92.000000,91.000000,84.000000,92.000000

### Write Summary for Above

In [32]:
fifa.describe(include=['category'])

,Name,Photo,Nationality,Flag,Club,Club Logo,Value,Wage,Acceleration,Aggression,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
count,17981,17981,17981,17981,17733,17981,17981,17981,17981,17981,...,17981,17981,17981,17981,17981,17981,17981,17981,17981,17981
unique,16975,17929,165,165,647,679,207,142,161,151,...,209,153,169,194,180,187,168,173,125,802
top,J. Williams,https://cdn.sofifa.org/48/18/players/223627.png,England,https://cdn.sofifa.org/flags/14.png,Villarreal CF,https://cdn.sofifa.org/24/18/teams/483.png,1.1M,1K,68,70,...,64,68,62,68,72,66,72,58,48,CB
freq,7,2,1630,1630,35,35,387,4201,706,495,...,807,556,504,759,624,559,627,537,413,2216

### Write Summary for Above

### Check for null values

In [33]:
fifa.isnull().sum()

Unnamed: 0        0
Name              0
Age               0
Photo             0
Nationality       0
               ...
RM             2029
RS             2029
RW             2029
RWB            2029
ST             2029
Length: 74, dtype: int64